### PR TITLE
Remodel

### PR DESCRIPTION
**Pull request by ChrisShank**

### CODE REVIEW

**Comment by ChrisShank** [comment]
uuug wrong repo

**Comment by andyjakubowski** [comment]
😃

**Comment by ChrisShank** [comment]
For context, some discourse about how one could remodel Harel's citizen watch https://www.youtube.com/watch?v=8W9cRC438Y4

**Comment by andyjakubowski** [comment]
Ah nice! I wrote you a follow-up email to your Gmail address.

**Pull request closed without merging**
